# Path to database file
db_path: "/data/url_evaluator/db.sqlite"

# Scheduler config
# Uses common cron-style format, e.g.:
#   hour: */4
#   minute: 15
scheduler:
  timezone: "UTC"
  honeynetasia2evaluator:
    hour: 12
    minute: 0
  tpot2evaluator:
    hour: 12
    minute: 2
  activity_scanner:
    hour: 12
    minute: 5
  db_cleaner:
    hour: 12
    minute: 25
  evaluator2urlhaus:
    hour: 12
    minute: 30
  evaluator2misp:
    hour: 12
    minute: 30

# Max age of inactive/invalid URLs
# Older records are automatically deleted
max_age_inactive: 30 # days
max_age_invalid: 7 # days

# Max size of downloaded content
max_file_size: 100 # MB

# How often should evaluation blacklist be updated
bl_update_time: 15 # minutes

# Threshold values for DDoS detection
ddos_threshold:
  same_url_single_session: 10
  same_domain_single_session: 100
  same_domain_all_sessions: 500

# HTTP proxy used for connections to suspicious URLs
# Keep empty if you aren't using a proxy
http_proxy: ""

# Warden client config
warden_config: "/etc/url_evaluator/warden_client.cfg"

# Warden filter (used by Warden client)
warden_filter:
  cat: "Intrusion.UserCompromise"

# Warden source mapping (dict[source -> dict[idea_field -> regex]])
# Events that do not match any of the listed patterns will be ignored
warden_sources:
  "CESNET Hugo":
    "Node.SW": "Cowrie with Warden Filer"
  "CZ.NIC HaaS":
    "Node.Name": "cznic_haas"
  "Warden (unknown node)": {}  # matches everything

# MISP
misp_url: "!!! CHANGE THIS !!!"
misp_key: "!!! CHANGE THIS !!!"
misp_verify_cert: false

# Virustotal
vt_url: "https://www.virustotal.com/api/v3/"
vt_key: "!!! CHANGE THIS !!!"
vt_minute_quota: 4
vt_threshold:
  malicious: 0.2
  harmless: 0.8

# URLhaus
urlhaus_blacklist_url: "https://urlhaus.abuse.ch/downloads/text/"
urlhaus_detail_url: "https://urlhaus-api.abuse.ch/v1/url/"
urlhaus_submit_url: "https://urlhaus.abuse.ch/api/"
urlhaus_key: "!!! CHANGE THIS !!!"

# MalwareBazaar
mb_url: "https://mb-api.abuse.ch/api/v1/"
mb_key: "!!! CHANGE THIS !!!"

# Honeynet.Asia
hna_url: "https://feeds.honeynet.asia/url/latest-url-unique.csv"

# T-Pot
tpot_url: "https://castor.security.psnc.pl/urls/long?days=1"
tpot_key: "!!! CHANGE THIS !!!"

# URL of Evaluator root (without trailing slash, e.g. "/url_evaluator")
# All evaluator pages are relative to this
# Keep empty if evaluator resides in web server's root directory
base_url: "/url_evaluator"

# Secret key used by Flask for various security purposes
# Should be set automatically during installation. If not, use e.g.:
#   head -c 24 /dev/urandom | base64
flask_secret_key: "!!! CHANGE THIS !!!"
