# URL Evaluator (Flask app) configuration for Apache

Define EvaluatorBaseLoc /url_evaluator
Define EvaluatorBaseLocS /url_evaluator/
Define EvaluatorBaseDir /url_evaluator/web

# Set up WSGI script
WSGIDaemonProcess url_evaluator_wsgi python-path=${EvaluatorBaseDir}
WSGIScriptAlias ${EvaluatorBaseLoc} ${EvaluatorBaseDir}/wsgi.py

<Location ${EvaluatorBaseLoc}>
    WSGIProcessGroup url_evaluator_wsgi
</Location>

<Directory ${EvaluatorBaseDir}>
    <Files wsgi.py>
        # Authentication using HTTP Authentication and local accounts ("htpasswd" file)
        AuthType basic
        AuthName "URL Evaluator web"
        AuthUserFile "/etc/url_evaluator/htpasswd"
        Require valid-user
        <IfDefine MAINTENANCE>
            # Redirect all requests to error 503 page and set it to a simple text message
            ErrorDocument 503 "Sorry, URL Evaluator is temporarily down due to maintenance and/or upgrade."
            RewriteEngine on
            # Exception for local connections - used for testing
            RewriteCond %{REMOTE_ADDR} !=127.0.0.1
            RewriteCond %{REMOTE_ADDR} !=::1
            RewriteRule ^ - [R=503,L]
        </IfDefine>
    </Files>
</Directory>

# Static files must be served directly by Apache, not by Flask
Alias ${EvaluatorBaseLocS}static/ ${EvaluatorBaseDir}/static/
<Directory ${EvaluatorBaseDir}/static>
    Require all granted
    # Remove timestamps from .css and .js files, which are added to the
    # filenames to force refresh of the files whenever they're modified.
    # (URLs are generated to point to e.g. /static/style.1234567890.css,
    # where the number is file modification time)
    RewriteEngine on
    RewriteBase ${EvaluatorBaseLocS}static/
    RewriteRule ^(.*)\.[\d]{10}\.(css|js)$ $1.$2 [L]
    #LogLevel alert rewrite:trace3
</Directory>

# API handlers
#<Location ${EvaluatorBaseLoc}/api>
#    # Pass Authorization header (useful if auth. is done by application using API keys passed in Authorization header)
#    WSGIPassAuthorization On
#    # Return JSON-formatted error message in case something goes wrong.
#    ErrorDocument 500 "{\"err_n\": 500, \"error\": \"Internal Server Error\"}"
#</Location>
